/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LauncherRouteImport } from './routes/launcher'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsPaneIdRouteImport } from './routes/sessions/$paneId'

const LauncherRoute = LauncherRouteImport.update({
  id: '/launcher',
  path: '/launcher',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsPaneIdRoute = SessionsPaneIdRouteImport.update({
  id: '/sessions/$paneId',
  path: '/sessions/$paneId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/launcher': typeof LauncherRoute
  '/sessions/$paneId': typeof SessionsPaneIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/launcher': typeof LauncherRoute
  '/sessions/$paneId': typeof SessionsPaneIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/launcher': typeof LauncherRoute
  '/sessions/$paneId': typeof SessionsPaneIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/launcher' | '/sessions/$paneId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/launcher' | '/sessions/$paneId'
  id: '__root__' | '/' | '/launcher' | '/sessions/$paneId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LauncherRoute: typeof LauncherRoute
  SessionsPaneIdRoute: typeof SessionsPaneIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/launcher': {
      id: '/launcher'
      path: '/launcher'
      fullPath: '/launcher'
      preLoaderRoute: typeof LauncherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$paneId': {
      id: '/sessions/$paneId'
      path: '/sessions/$paneId'
      fullPath: '/sessions/$paneId'
      preLoaderRoute: typeof SessionsPaneIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LauncherRoute: LauncherRoute,
  SessionsPaneIdRoute: SessionsPaneIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
